"""update SpendingConfig fields to nullable

Revision ID: 1e8a69ff708e
Revises: e5abe24977cc
Create Date: 2026-04-07 16:26:04.446209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8a69ff708e'
down_revision: Union[str, None] = 'e5abe24977cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spending_config', 'income_window',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'3'::smallint"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spending_config', 'income_window',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'3'::smallint"))
    # ### end Alembic commands ###
