"""fix init user table

Revision ID: 4793700fa7b9
Revises: b2e55b80b0a3
Create Date: 2026-03-19 21:43:18.966676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4793700fa7b9'
down_revision: Union[str, None] = 'b2e55b80b0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_transaction',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.Column('original_mcc', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('operation_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.SmallInteger(), nullable=False),
    sa.Column('commission_rate', sa.BigInteger(), nullable=False),
    sa.Column('cashback_amount', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('hold', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('receipt_id', sa.String(length=128), nullable=True),
    sa.Column('counter_edrpou', sa.String(length=32), nullable=True),
    sa.Column('counter_iban', sa.String(length=64), nullable=True),
    sa.Column('counter_name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_user_transaction_time'), 'user_transaction', ['time'], unique=False)
    op.create_index(op.f('ix_user_transaction_user_id'), 'user_transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_transaction_user_id'), table_name='user_transaction')
    op.drop_index(op.f('ix_user_transaction_time'), table_name='user_transaction')
    op.drop_table('user_transaction')
    op.drop_table('user')
    # ### end Alembic commands ###
