"""add user_account table

Revision ID: 625aaea8cb0b
Revises: 1d2e74bfa8e1
Create Date: 2026-04-01 17:53:15.856586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625aaea8cb0b'
down_revision: Union[str, None] = '1d2e74bfa8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_account_id'), 'user_account', ['account_id'], unique=True)
    op.create_index(op.f('ix_user_account_user_id'), 'user_account', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_user_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_account_id'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
