"""update spending config

Revision ID: 8bdaed46bf4d
Revises: e35551190d22
Create Date: 2026-04-06 19:45:55.360001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdaed46bf4d'
down_revision: Union[str, None] = 'e35551190d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_config', sa.Column('income_day', sa.SmallInteger(), nullable=False))
    op.add_column('spending_config', sa.Column('income_window', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending_config', 'income_window')
    op.drop_column('spending_config', 'income_day')
    # ### end Alembic commands ###
