"""Added set_income field in SpendingConfig

Revision ID: a6209bee4af7
Revises: 1e8a69ff708e
Create Date: 2026-04-08 17:59:01.856986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6209bee4af7'
down_revision: Union[str, None] = '1e8a69ff708e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_config', sa.Column('set_income', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending_config', 'set_income')
    # ### end Alembic commands ###
