"""extend user_account and add account_id to user_transaction

Revision ID: b1200b9bef75
Revises: 625aaea8cb0b
Create Date: 2026-04-02 23:38:44.138708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1200b9bef75'
down_revision: Union[str, None] = '625aaea8cb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcc_category',
    sa.Column('mcc_code', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.Column('category_group', sa.String(length=32), nullable=False),
    sa.Column('display_name_uk', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcc_category_mcc_code'), 'mcc_category', ['mcc_code'], unique=True)
    op.add_column('user_account', sa.Column('currency_code', sa.SmallInteger(), nullable=True))
    op.add_column('user_account', sa.Column('account_type', sa.String(length=32), nullable=True))
    op.add_column('user_account', sa.Column('display_name', sa.String(length=128), nullable=True))
    op.add_column('user_transaction', sa.Column('account_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_transaction_account_id'), 'user_transaction', ['account_id'], unique=False)
    op.create_index('ix_user_transaction_account_time', 'user_transaction', ['account_id', 'time'], unique=False)
    op.create_foreign_key(None, 'user_transaction', 'user_account', ['account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_transaction', type_='foreignkey')
    op.drop_index('ix_user_transaction_account_time', table_name='user_transaction')
    op.drop_index(op.f('ix_user_transaction_account_id'), table_name='user_transaction')
    op.drop_column('user_transaction', 'account_id')
    op.drop_column('user_account', 'display_name')
    op.drop_column('user_account', 'account_type')
    op.drop_column('user_account', 'currency_code')
    op.drop_index(op.f('ix_mcc_category_mcc_code'), table_name='mcc_category')
    op.drop_table('mcc_category')
    # ### end Alembic commands ###
