"""update income date field

Revision ID: e5abe24977cc
Revises: 8bdaed46bf4d
Create Date: 2026-04-06 19:47:58.859158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5abe24977cc'
down_revision: Union[str, None] = '8bdaed46bf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_config', sa.Column('income_day', sa.SmallInteger(), nullable=True))
    op.add_column('spending_config', sa.Column('income_window', sa.SmallInteger(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending_config', 'income_window')
    op.drop_column('spending_config', 'income_day')
    # ### end Alembic commands ###
